name: Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *'   # ← было */14, стало каждые 10 минут
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://easyvietnam-c7b6.onrender.com
